# GLM intro




Data from: https://www.openicpsr.org/openicpsr/project/116023/version/V1/view?path=/openicpsr/116023/fcr:versions/V1/lakisha_aer.dta&type=file

In [6]:
%reset -f

In [1]:
import numpy             as np
import statsmodels.api   as sm
import pandas            as pd
import seaborn           as sns

from statsmodels.discrete.discrete_model import LogitResults

from statsmodels.iolib.summary2 import summary_col

In [2]:
df = pd.read_stata("/home/michael/Projects/regression_analysis/data/lakisha_aer.dta")

In [3]:
df = sm.add_constant(df)
df.columns

Index(['const', 'id', 'ad', 'education', 'ofjobs', 'yearsexp', 'honors',
       'volunteer', 'military', 'empholes', 'occupspecific', 'occupbroad',
       'workinschool', 'email', 'computerskills', 'specialskills', 'firstname',
       'sex', 'race', 'h', 'l', 'call', 'city', 'kind', 'adid', 'fracblack',
       'fracwhite', 'lmedhhinc', 'fracdropout', 'fraccolp', 'linc', 'col',
       'expminreq', 'schoolreq', 'eoe', 'parent_sales', 'parent_emp',
       'branch_sales', 'branch_emp', 'fed', 'fracblack_empzip',
       'fracwhite_empzip', 'lmedhhinc_empzip', 'fracdropout_empzip',
       'fraccolp_empzip', 'linc_empzip', 'manager', 'supervisor', 'secretary',
       'offsupport', 'salesrep', 'retailsales', 'req', 'expreq', 'comreq',
       'educreq', 'compreq', 'orgreq', 'manuf', 'transcom', 'bankreal',
       'trade', 'busservice', 'othservice', 'missind', 'ownership'],
      dtype='object')

In [4]:
df.head()

,const,id,ad,education,ofjobs,yearsexp,honors,volunteer,military,empholes,...,compreq,orgreq,manuf,transcom,bankreal,trade,busservice,othservice,missind,ownership
0,1.0,b,1,4,2,6,0,0,0,1,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
1,1.0,b,1,3,3,6,0,1,1,0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
2,1.0,b,1,4,1,6,0,0,0,0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,1.0,b,1,3,4,6,0,1,0,1,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,1.0,b,1,3,3,22,0,0,0,0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit

In [5]:
df.describe()

,const,education,ofjobs,yearsexp,honors,volunteer,military,empholes,occupspecific,occupbroad,...,educreq,compreq,orgreq,manuf,transcom,bankreal,trade,busservice,othservice,missind
count,4870.0,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,...,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000
mean,1.0,3.618480,3.661396,7.842916,0.052772,0.411499,0.097125,0.448049,215.637782,3.481520,...,0.106776,0.437166,0.072690,0.082957,0.030390,0.085010,0.213963,0.267762,0.154825,0.165092
std,0.0,0.714997,1.219126,5.044612,0.223601,0.492156,0.296159,0.497345,148.127551,2.038036,...,0.308866,0.496083,0.259649,0.275854,0.171677,0.278932,0.410141,0.442847,0.361773,0.371308
min,1.0,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.0,3.000000,3.000000,5.000000,0.000000,0.000000,0.000000,0.000000,27.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.0,4.000000,4.000000,6.000000,0.000000,0.000000,0.000000,0.000000,267.000000,4.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.0,4.000000,4.000000,9.000000,0.000000,1.000000,0.000000,1.000000,313.000000,6.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,1.0,4.000000,7.000000,44.000000,1.000000,1.000000,1.000000,1.000000,903.000000,6.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
X = [['const', 'nwifeinc', 'educ', 'exper', 'expersq', 'age', 'kidslt6']]
y = ""

# OLS coefficients and Marginal effect table
## since OLS coefficient is the ME, there is no need to output another table

In [82]:
ols_mod = sm.OLS(Y, X)
ols_res = ols_mod.fit(cov_type='HC1')

print(ols_res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   inlf   R-squared:                       0.263
Model:                            OLS   Adj. R-squared:                  0.257
Method:                 Least Squares   F-statistic:                     72.28
Date:                Mon, 24 May 2021   Prob (F-statistic):           5.53e-71
Time:                        12:26:20   Log-Likelihood:                -424.38
No. Observations:                 753   AIC:                             862.8
Df Residuals:                     746   BIC:                             895.1
Df Model:                           6
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6509      0.140      4.634      0.000       0.376       0.926
nwifeinc      -0.0033      0.002     -2.189      0.029      -0.006      -0.000
educ           0.0373      0.007      5.151      0.000       0.023       0.051
exper          0.0391      0.006      6.754      0.000       0.028       0.050
expersq       -0.0006      0.000     -3.138      0.002      -0.001      -0.000
age           -0.0169      0.002     -7.452      0.000      -0.021      -0.012
kidslt6       -0.2655      0.032     -8.364      0.000      -0.328      -0.203
==============================================================================
Omnibus:                      175.416   Durbin-Watson:                   0.493
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               36.815
Skew:                          -0.187   Prob(JB):                     1.01e-08
Kurtosis:                       1.984   Cond. No.                     2.77e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.77e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

# Probit coefficients and Marginal effect table

In [83]:
probit_mod = sm.Probit(Y, X)
probit_res = probit_mod.fit(cov_type='HC1')

print(probit_res.summary())

Optimization terminated successfully.
         Current function value: 0.533394
         Iterations 5
                          Probit Regression Results
==============================================================================
Dep. Variable:                   inlf   No. Observations:                  753
Model:                         Probit   Df Residuals:                      746
Method:                           MLE   Df Model:                            6
Date:                Mon, 24 May 2021   Pseudo R-squ.:                  0.2199
Time:                        12:26:30   Log-Likelihood:                -401.65
converged:                       True   LL-Null:                       -514.87
Covariance Type:                  HC1   LLR p-value:                 4.369e-46
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4634      0.449      1.031      0.302      -0.417       1.344
nwifeinc      -0.0118      0.005     -2.225      0.026      -0.022      -0.001
educ           0.1287      0.026      5.029      0.000       0.079       0.179
exper          0.1221      0.019      6.532      0.000       0.085       0.159
expersq       -0.0019      0.001     -3.149      0.002      -0.003      -0.001
age           -0.0553      0.008     -7.058      0.000      -0.071      -0.040
kidslt6       -0.8809      0.116     -7.605      0.000      -1.108      -0.654
==============================================================================

In [86]:
probit_me = probit_res.get_margeff()
print(probit_me.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:                   inlf
Method:                          dydx
At:                           overall
==============================================================================
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
nwifeinc      -0.0036      0.002     -2.253      0.024      -0.007      -0.000
educ           0.0387      0.007      5.271      0.000       0.024       0.053
exper          0.0368      0.005      7.092      0.000       0.027       0.047
expersq       -0.0006      0.000     -3.205      0.001      -0.001      -0.000
age           -0.0167      0.002     -7.713      0.000      -0.021      -0.012
kidslt6       -0.2652      0.031     -8.446      0.000      -0.327      -0.204
==============================================================================

# Loit coefficients and Marginal effect table

In [87]:
logit_mod = sm.Logit(Y, X)
logit_res = logit_mod.fit(cov_type='HC1')

print(logit_res.summary())

Optimization terminated successfully.
         Current function value: 0.533983
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                   inlf   No. Observations:                  753
Model:                          Logit   Df Residuals:                      746
Method:                           MLE   Df Model:                            6
Date:                Mon, 24 May 2021   Pseudo R-squ.:                  0.2191
Time:                        12:26:43   Log-Likelihood:                -402.09
converged:                       True   LL-Null:                       -514.87
Covariance Type:                  HC1   LLR p-value:                 6.756e-46
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.7502      0.758      0.990      0.322      -0.736       2.236
nwifeinc      -0.0210      0.009     -2.310      0.021      -0.039      -0.003
educ           0.2176      0.044      4.936      0.000       0.131       0.304
exper          0.2037      0.032      6.381      0.000       0.141       0.266
expersq       -0.0031      0.001     -3.128      0.002      -0.005      -0.001
age           -0.0922      0.013     -6.831      0.000      -0.119      -0.066
kidslt6       -1.4682      0.202     -7.259      0.000      -1.865      -1.072
==============================================================================

In [88]:
logit_me = logit_res.get_margeff()
print(logit_me.summary())

        Logit Marginal Effects
=====================================
Dep. Variable:                   inlf
Method:                          dydx
At:                           overall
==============================================================================
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
nwifeinc      -0.0038      0.002     -2.350      0.019      -0.007      -0.001
educ           0.0389      0.007      5.224      0.000       0.024       0.054
exper          0.0364      0.005      7.050      0.000       0.026       0.047
expersq       -0.0006      0.000     -3.200      0.001      -0.001      -0.000
age           -0.0165      0.002     -7.572      0.000      -0.021      -0.012
kidslt6       -0.2625      0.032     -8.220      0.000      -0.325      -0.200
==============================================================================

In [89]:
hypotheses = '(exper = expersq), (exper = 0)'
f_test = logit_res.wald_test(hypotheses)

print(f_test)

<Wald test (chi2): statistic=[[90.87993652]], p-value=1.843624736087094e-20, df_denom=2>

# GLM coefficient comparison table

In [90]:
info_dict={'R2' : lambda x: f"{x.rsquared:.2f}",
           'Pseudo R2' : lambda x: f"{x.prsquared:.2f}",
           'No. observations' : lambda x: f"{int(x.nobs):d}"}

results_table = summary_col(results=[ols_res, probit_res, logit_res],
                            float_format='%0.4f',
                            stars = True,
                            model_names=['OLS',
                                         'Probit',
                                         'Logit'],
                            info_dict=info_dict,
                            regressor_order=['const','nwifeinc', 'educ', 
                                             'exper', 'expersq', 'age', 
                                             'kidslt6'])

results_table.add_title('GLM coefficient comparison')

print(results_table)

           GLM coefficient comparison
=================================================
                    OLS       Probit     Logit
-------------------------------------------------
const            0.6509***  0.4634     0.7502
                 (0.1405)   (0.4493)   (0.7581)
nwifeinc         -0.0033**  -0.0118**  -0.0210**
                 (0.0015)   (0.0053)   (0.0091)
educ             0.0373***  0.1287***  0.2176***
                 (0.0072)   (0.0256)   (0.0441)
exper            0.0391***  0.1221***  0.2037***
                 (0.0058)   (0.0187)   (0.0319)
expersq          -0.0006*** -0.0019*** -0.0031***
                 (0.0002)   (0.0006)   (0.0010)
age              -0.0169*** -0.0553*** -0.0922***
                 (0.0023)   (0.0078)   (0.0135)
kidslt6          -0.2655*** -0.8809*** -1.4682***
                 (0.0317)   (0.1158)   (0.2023)
R-squared        0.2633
R-squared Adj.   0.2573
R2               0.26
Pseudo R2                   0.22       0.22
No. observations 753        753        753
=================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

# GLM ME table
## note that, there is no Marginal Effect comparison table; hence, I am writing one myself

In [91]:
me_OLS_col = np.array(ols_res.params[1::])
p_OLS_col  = np.array(ols_res.pvalues[1::])
me_Pro_col = probit_me.margeff
p_Pro_col  = probit_me.pvalues
me_Log_col = logit_me.margeff
p_Log_col  = logit_me.pvalues

df1 = pd.concat([pd.DataFrame({'vari':['nwifeinc','educ', 'exper', 'expersq', 'age', 'kidslt6']}), 
                 pd.DataFrame({'OLS ME': me_OLS_col.round(4)}),
                 pd.DataFrame({'OLS p-val': p_OLS_col.round(2)}),
                 pd.DataFrame({'Probit ME': me_Pro_col.round(4)}),
                 pd.DataFrame({'Probit p-val': p_Pro_col.round(2)}),
                 pd.DataFrame({'Logit ME': me_Log_col.round(4)}),
                 pd.DataFrame({'Logit p-val': p_Log_col.round(2)})],
                axis=1, join='inner')

In [92]:
df1

       vari  OLS ME  OLS p-val  Probit ME  Probit p-val  Logit ME  Logit p-val
0  nwifeinc -0.0033       0.03    -0.0036          0.02   -0.0038         0.02
1      educ  0.0373       0.00     0.0387          0.00    0.0389         0.00
2     exper  0.0391       0.00     0.0368          0.00    0.0364         0.00
3   expersq -0.0006       0.00    -0.0006          0.00   -0.0006         0.00
4       age -0.0169       0.00    -0.0167          0.00   -0.0165         0.00
5   kidslt6 -0.2655       0.00    -0.2652          0.00   -0.2625         0.00

In [93]:
!rm -rf Week10_Python.html
!jupyter nbconvert --to html Week10_Python.ipynb

[NbConvertApp] Converting notebook Week10_Python.ipynb to html
[NbConvertApp] Writing 609519 bytes to Week10_Python.html